### ISSUE TITLE
JSON TypeError

### ISSUE THREAD

**Issue by rostam2000** [xdever/OnyxNoteRenderer#1]
Thanks for creating this excellent tool. While trying to go through a zip backup file (approx 72MB, containing dozens of notes), the following message appears and terminates the procedure soon after starting with the first pdf:

`Traceback (most recent call last):
  File "./onyx_render.py", line 203, in <module>
    render(zip_name, save_to, names)
  File "./onyx_render.py", line 192, in render
    render_pdf(note, tmpdir, fname)
  File "./onyx_render.py", line 118, in render_pdf
    matrix = np.asarray(json.loads(matrix)["values"], dtype=np.float32).reshape(3,3)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType`

Could you kindly advise on how to fix this?

**Comment by RobertCsordas** [comment]
Could you try it now, please?

It turns out that they changed the file format in the recent firmware versions, and it works only with the notes written with the new firmware. Now I changed the program in a very hacky way to not crash if anything went wrong during rendering, so it could still render the new notes.

**Comment by RobertCsordas** [comment]
It should work now.
